language: python
python:
- '2.7'
branches:
  only:
  - pelican
install:
- pip install -r requirements.txt
script:
- make publish
deploy:
  provider: pages
  local_dir: ./output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: pelican

